---
# https://github.com/marketplace/actions/super-linter

name: Lint Code Base

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v2
        with:
          # We need a full repo clone
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MULTI_STATUS: true
          VALIDATE_BASH: true
